/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/more': RouteRecordInfo<'/more', '/more', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
    '/stardew_valley/mod': RouteRecordInfo<'/stardew_valley/mod', '/stardew_valley/mod', Record<never, never>, Record<never, never>>,
    '/stardew_valley/online': RouteRecordInfo<'/stardew_valley/online', '/stardew_valley/online', Record<never, never>, Record<never, never>>,
    '/stardew_valley/save': RouteRecordInfo<'/stardew_valley/save', '/stardew_valley/save', Record<never, never>, Record<never, never>>,
    '/stardew_valley/setting': RouteRecordInfo<'/stardew_valley/setting', '/stardew_valley/setting', Record<never, never>, Record<never, never>>,
    '/stardew_valley/toolbox': RouteRecordInfo<'/stardew_valley/toolbox', '/stardew_valley/toolbox', Record<never, never>, Record<never, never>>,
    '/suggest': RouteRecordInfo<'/suggest', '/suggest', Record<never, never>, Record<never, never>>,
  }
}
