/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Conf': RouteRecordInfo<'/Conf', '/Conf', Record<never, never>, Record<never, never>>,
    '/GameSave': RouteRecordInfo<'/GameSave', '/GameSave', Record<never, never>, Record<never, never>>,
    '/ModManager': RouteRecordInfo<'/ModManager', '/ModManager', Record<never, never>, Record<never, never>>,
    '/More': RouteRecordInfo<'/More', '/More', Record<never, never>, Record<never, never>>,
    '/Toolbox': RouteRecordInfo<'/Toolbox', '/Toolbox', Record<never, never>, Record<never, never>>,
  }
}
